### ISSUE TITLE
Failed installing RAMPART-develop

### ISSUE THREAD

**Issue by MaestSi** [TGAC/RAMPART#30]
Dear Daniel,
after installing "git" and "maven3.3.9", and downloading "RAMPART-develop" branch with command "git clone https://github.com/TGAC/RAMPART.git" I commented the "create manual execution" element and tried to install typing "mvn clean install" after "cd RAMPART".
This gave error:
"Could not resolve dependencies for project uk.ac.tgac.rampart:rampart:jar:0.12.3: Failure to find uk.ac.tgac.conan:tgac-conan-process-wrappers:jar:0.12.9 in https://repos.tgac.ac.uk/maven/repo"

Then, I looked at "https://repos.tgac.ac.uk/maven/repo/uk/ac/tgac/conan/tgac-conan-process-wrappers/" and saw there isn't a 0.12.9 directory.
I also tried to modify the pom.xml file in:

```
<dependency>
            <groupId>uk.ac.tgac.conan</groupId>
            <artifactId>tgac-conan-process-wrappers</artifactId>
            <version>0.12.9</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-cli</groupId>
                    <artifactId>commons-cli</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

substituting 0.12.9 with 0.12.1 and this didn't give the same errors as before but gave many compilation errors.
How can I install RAMPART-develop version?
Thank you

**Comment by maplesond** [comment]
Hello,

It appears as though our repo server hasn't been updated with the latest dependencies.  I'll take a look into this later.  In the meantime, the best way to circumvent this problem is to get conan and tgac-conan-procs installed into your local maven repo.

To do that you need to clone and then `mvn clean install` this repo:
[https://github.com/TGAC/conan](https://github.com/TGAC/conan)

.. and then this one:
[https://github.com/TGAC/TgacConanProcs](https://github.com/TGAC/TgacConanProcs)

... and then run `mvn clean install` on your RAMPART develop code.

**Comment by MaestSi** [comment]
Thank you, in this way RAMPART v 0.12.3 runs, but still doesn't allow to provide additional arguments to QUAST, e. g. :

```
<tool name="QUAST" threads="8" memory="10000" unchecked_args="--min-contig=400"/>
```

Is it in some way expected?

**Comment by MaestSi** [comment]
Sorry, my fault, I didn't notice the new version is 0.12.4, now it works!
 "git clone https://github.com/TGAC/RAMPART.git" downloads the last "master" branch, of course, that is 0.12.3.

**Comment by maplesond** [comment]
Great!  Glad it's working.
